---
title: "Logistic regression"
author: "Mathew Yang"
date: "November 27, 2017"
output: html_document
---

```{r}
library(caret)
library(pROC)
#Load data
wdbc = read.csv("wdbc.data", header= FALSE)
#only the means
wdbc.means = wdbc[2:12]
```

#Logisitic Regression
```{r}
#Logistic regression on means.
#Train and test on same dataset.
cancer.fit = glm(V2~V3 + V4 + V5 + V6 + V7 + V8 + V9 + V10 + V11 + V12, data=wdbc.means, family= binomial)
summary(cancer.fit)
```

V4,V6,V7,V10 showed significance. This was training and testing on the same dataset. 
```{r}
#Gives probabilities that the observation is a malignant tumor. Probability close to 1 is malignant, 0 is benign.
cancer.probs = predict(cancer.fit, type = "response")

#Create a vector of 569 Benign elements
cancer.pred=rep("B",569)

#Transform all the ones greate than 0.5 to Malignant.
cancer.pred[cancer.probs>0.5]="M"
```
Confusion Matrix
```{r}
table(cancer.pred, wdbc$V2)
```

Training error rate is 1 - (347+193)/569 = 0.051, which means that the model was capable of correctly guessing M or B almost 95% of the time. This needs to be retested via crossvalidation or LOOCV.

```{r}
#10-fold cross validation
ctrl <- trainControl(method = "repeatedcv", number = 10, savePredictions = TRUE)

mod_fit <- train(V2~V3 + V4 + V5 + V6 + V7 + V8 + V9 + V10 + V11 + V12, 
                 data=wdbc.means, method="glm", family="binomial",
                 trControl = ctrl)
```

```{r}
# Select a parameter setting
selectedIndices <- mod_fit$pred
# Plot:
plot.roc(mod_fit$pred$obs[selectedIndices],
         mod_fit$pred$M[selectedIndices])
```


```{r}
pred = predict(mod_fit, newdata = wdbc.means)
confusionMatrix(data=pred, wdbc.means$V2)
```


